
spring:
  devtools:
    livereload:
      port: 35732
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yangpi
      routes:
        - id: api_route
          uri: http://localhost:8123  #
          predicates:
            - Path=/api/**
server:
  port: 8090

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-custom
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
